# Set theme
remote_theme: daviddarnes/garth

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-paginate
- jekyll-remote-theme

# Site settings
url: 'https://liyuezhao.github.io/'
baseurl: ''
title: 'Yuezhao Li'
description: 'Homepage'
permalink: pretty
logo: "https://liyuezhao.github.io/pics/site_logo.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: ""
